@startuml Track object
class Timeline{
    +iterator(): Iterator<Track>
    +hasTrack(UUID): boolean
    +getTrack(UUID): Optional<Track>
    +addTrack(Track): void
    +removeTrack(UUID): boolean
    +isMutable(): boolean
    +setMutable(boolean): void
    +copy(boolean): Timeline
}

class Track{
    + getId(): UUID
    + iterator(): Iterator<Clip>
    + hasClip(UUID): boolean
    + getClip(UUID): Optional<Clip>
    + addClip(Clip): void
    + removeClip(UUID) boolean
    + isMutable(): boolean
    + setMutable(boolean): void
    + copy(boolean): Track

}
Timeline<|.. Track

@enduml

