
@startuml event object
abstract class Event {
+ apply(EventContext<T>):EventResult
}
abstract class TrackEvent{
+getTrackId(): UUID
}
abstract class TimelineEvent{

}
abstract class ClipEvent{
 +getTrackId(): UUID
 +getClipId(): UUID
}
record EventContext{
    target(): T
    timeline(): Timeline
    track(): Track
}

Event <|.. ClipEvent
Event <|.. TrackEvent
Event <|.. TimelineEvent

@enduml


note: having EventContext<T> breaks the UML
