@startuml Note object
record Note {
    + pitch(): Pitch
    + position(): float
    + duration(): float
    + volume(): float
    + modifyPitch(Function<Pitch, Pitch>): Note
    + modifyPosition(Function<Float, Float>): Note
    + modifyDuration(Function<Float, Float>): Note
    + modifyVolume(Function<Float, Float>): Note
}
@enduml
