@startuml pitchName object
enum PitchName {
    + next(): PitchName
    + next(int): PitchName
    + previous(): PitchName
    + previous(int): PitchName
    + isSharp(): boolean
    + isFlat(): boolean
    + isNatural(): boolean
    + getOctaveOffset(): int
    + toString(): String
    + {static} tryParse(String): Optional<PitchName>
}
@enduml
