@startuml Pitch object
record Pitch {
    + name(): PitchName
    + octave(): int
    + toMidi(): int
    + {static} fromMidi(int,boolen): Pitch
    + addSemitones(int): Pitch
    + addSemitones(int, boolean): Pitch
    + compareTo(Pitch): int
    + equals(Object): boolean
    + {static} tryParse(String): Optional<Pitch>
    }
@enduml
